import type { QuizSet } from './types'

/**
 * Metadata-only quiz sets. `questions` is empty here — fully seeded sets
 * are exported from `lib/questions/<id>.ts` and merged in by
 * `lib/questions/index.ts`.
 */
export const QUIZ_SETS: QuizSet[] = [
  // ===== Lập trình =====
  {
    id: 'ts-basics',
    category: 'code',
    title: 'TypeScript căn bản',
    desc: 'Type, interface, generic, narrowing — những thứ bạn dùng mỗi ngày.',
    icon: 'TS',
    iconMono: true,
    tint: '#dcd5ff',
    inkOfTint: '#3142a8',
    level: 'easy',
    questions: [],
    minutes: 15,
    progress: 0.62,
    section: 'đang học',
  },
  {
    id: 'react-hooks',
    category: 'code',
    title: 'React Hooks sâu',
    desc: 'useEffect, useMemo, useCallback và những bẫy quen thuộc.',
    icon: '⚛',
    tint: '#cfeeff',
    inkOfTint: '#0a6e90',
    level: 'mid',
    questions: [],
    minutes: 22,
    progress: 0.18,
    section: 'đang học',
  },
  {
    id: 'js-quirks',
    category: 'code',
    title: 'JavaScript kỳ quặc',
    desc: 'this, hoisting, closure, == vs === — những đoạn code khiến bạn bối rối.',
    icon: 'JS',
    iconMono: true,
    tint: '#fff1c2',
    inkOfTint: '#7d5c00',
    level: 'easy',
    questions: [],
    minutes: 18,
    progress: 1,
    section: 'đã hoàn thành',
  },
  {
    id: 'css-modern',
    category: 'code',
    title: 'CSS hiện đại',
    desc: 'Grid, Flexbox, container query, :has(), color-mix() và các selector mới.',
    icon: '{ }',
    iconMono: true,
    tint: '#ffd6e9',
    inkOfTint: '#9c2865',
    level: 'mid',
    questions: [],
    minutes: 20,
    progress: 0,
    section: 'khám phá',
    isNew: true,
  },
  // ===== Tiếng Anh =====
  {
    id: 'en-irregular',
    category: 'english',
    title: 'Động từ bất quy tắc',
    desc: 'go-went-gone, take-took-taken… 100 động từ phổ biến nhất.',
    icon: '🔤',
    tint: '#cfeeff',
    inkOfTint: '#0a6e90',
    level: 'easy',
    questions: [],
    minutes: 12,
    progress: 0.45,
    section: 'đang học',
  },
  {
    id: 'en-toeic',
    category: 'english',
    title: 'TOEIC từ vựng 600',
    desc: 'Bộ 600 từ thường gặp trong đề thi TOEIC, có ví dụ ngắn.',
    icon: '📚',
    tint: '#ffd6c2',
    inkOfTint: '#9c3a14',
    level: 'mid',
    questions: [],
    minutes: 25,
    progress: 0,
    section: 'khám phá',
  },
  {
    id: 'en-phrasal',
    category: 'english',
    title: 'Phrasal verbs',
    desc: 'give up, look forward to, run into… cụm động từ người bản ngữ dùng hàng ngày.',
    icon: '💬',
    tint: '#e0d5ff',
    inkOfTint: '#4f3fb8',
    level: 'mid',
    questions: [],
    minutes: 20,
    progress: 0,
    section: 'khám phá',
    isNew: true,
  },
  {
    id: 'en-idioms',
    category: 'english',
    title: 'Thành ngữ thông dụng',
    desc: 'Break a leg, hit the road, piece of cake — hiểu đúng và dùng đúng.',
    icon: '🎯',
    tint: '#ffe0b3',
    inkOfTint: '#a36a10',
    level: 'hard',
    questions: [],
    minutes: 18,
    progress: 0,
    section: 'khám phá',
  },
  // ===== Con vật & Thiên nhiên =====
  {
    id: 'animal-jungle',
    category: 'animal',
    title: 'Động vật rừng nhiệt đới',
    desc: 'Báo, vẹt, lười, rắn… nhận biết qua hình ảnh và đặc điểm.',
    icon: '🦜',
    tint: '#cdf0c1',
    inkOfTint: '#1d6b2a',
    level: 'easy',
    questions: [],
    minutes: 14,
    progress: 0.3,
    section: 'đang học',
  },
  {
    id: 'animal-ocean',
    category: 'animal',
    title: 'Sinh vật biển',
    desc: 'Cá voi, bạch tuộc, sứa, san hô — đại dương rộng lớn đang chờ bạn.',
    icon: '🐙',
    tint: '#cfeeff',
    inkOfTint: '#0a6e90',
    level: 'easy',
    questions: [],
    minutes: 12,
    progress: 0,
    section: 'khám phá',
    isNew: true,
  },
  {
    id: 'animal-bird',
    category: 'animal',
    title: 'Các loài chim Việt Nam',
    desc: 'Chào mào, chích chòe, chim sâu, sếu đầu đỏ — đặc trưng từng vùng.',
    icon: '🐦',
    tint: '#ffe0b3',
    inkOfTint: '#a36a10',
    level: 'mid',
    questions: [],
    minutes: 18,
    progress: 0,
    section: 'khám phá',
  },
  {
    id: 'animal-extinct',
    category: 'animal',
    title: 'Loài đã tuyệt chủng',
    desc: 'Khủng long, voi ma mút, dodo… hành trình của những loài đã biến mất.',
    icon: '🦕',
    tint: '#e8d5c4',
    inkOfTint: '#6a4a2a',
    level: 'hard',
    questions: [],
    minutes: 16,
    progress: 0,
    section: 'khám phá',
  },
  // ===== Trắc nghiệm vui =====
  {
    id: 'fun-emoji',
    category: 'fun',
    title: 'Đoán phim qua emoji',
    desc: '🦁👑 → Vua sư tử. Đố bạn đoán được hết 30 phim nổi tiếng.',
    icon: '🎬',
    tint: '#ffd6e9',
    inkOfTint: '#9c2865',
    level: 'easy',
    questions: [],
    minutes: 10,
    progress: 0,
    section: 'khám phá',
    isNew: true,
  },
  {
    id: 'fun-personality',
    category: 'fun',
    title: 'Bạn giống nhân vật nào?',
    desc: '10 câu hỏi vui để tìm xem bạn giống nhân vật anime nào nhất.',
    icon: '✨',
    tint: '#e0d5ff',
    inkOfTint: '#4f3fb8',
    level: 'easy',
    questions: [],
    minutes: 5,
    progress: 0,
    section: 'khám phá',
  },
  {
    id: 'fun-trivia',
    category: 'fun',
    title: 'Trivia kỳ quặc',
    desc: 'Sự thật bất ngờ về vũ trụ, cơ thể người, lịch sử... bạn có tin không?',
    icon: '🤔',
    tint: '#fff1c2',
    inkOfTint: '#7d5c00',
    level: 'mid',
    questions: [],
    minutes: 12,
    progress: 0.08,
    section: 'đang học',
  },
  // ===== Địa lý & Lịch sử =====
  {
    id: 'geo-flags',
    category: 'world',
    title: 'Cờ các quốc gia',
    desc: '100 lá cờ phổ biến — từ G7 đến những đảo quốc nhỏ bé.',
    icon: '🏳',
    tint: '#ffd6c2',
    inkOfTint: '#9c3a14',
    level: 'mid',
    questions: [],
    minutes: 15,
    progress: 0,
    section: 'khám phá',
  },
  {
    id: 'geo-capital',
    category: 'world',
    title: 'Thủ đô thế giới',
    desc: 'Pháp → Paris, Việt Nam → Hà Nội. Còn Kazakhstan thì sao?',
    icon: '🌍',
    tint: '#cdf0c1',
    inkOfTint: '#1d6b2a',
    level: 'mid',
    questions: [],
    minutes: 18,
    progress: 0,
    section: 'khám phá',
  },
  {
    id: 'history-vn',
    category: 'world',
    title: 'Lịch sử Việt Nam',
    desc: 'Các triều đại, sự kiện và nhân vật quan trọng từ Hùng Vương đến nay.',
    icon: '📜',
    tint: '#ffe0b3',
    inkOfTint: '#a36a10',
    level: 'hard',
    questions: [],
    minutes: 30,
    progress: 0,
    section: 'khám phá',
    locked: true,
  },
  // ===== Khoa học =====
  {
    id: 'sci-space',
    category: 'science',
    title: 'Hành tinh & vũ trụ',
    desc: 'Hệ mặt trời, hố đen, Big Bang — từ những điều cơ bản nhất.',
    icon: '🪐',
    tint: '#dcd5ff',
    inkOfTint: '#3142a8',
    level: 'mid',
    questions: [],
    minutes: 18,
    progress: 0,
    section: 'khám phá',
    isNew: true,
  },
  {
    id: 'sci-body',
    category: 'science',
    title: 'Cơ thể người',
    desc: 'Tim đập bao nhiêu lần một ngày? Não nặng bao nhiêu? Khám phá nhé.',
    icon: '🧠',
    tint: '#ffd6e9',
    inkOfTint: '#9c2865',
    level: 'easy',
    questions: [],
    minutes: 14,
    progress: 0,
    section: 'khám phá',
  },
]
