import type { Question, QuizSet } from './types'

const reactHooksQuestions: Question[] = [
  { id: 1, title: 'useState — cú pháp cơ bản', section: 'useState' },
  { id: 2, title: 'Lazy initial state với callback', section: 'useState' },
  { id: 3, title: 'Functional setState — tránh stale state', section: 'useState' },
  { id: 4, title: 'Object state — spread pattern', section: 'useState' },
  { id: 5, title: 'useEffect — dependency array', section: 'useEffect' },
  { id: 6, title: 'Cleanup function trong useEffect', section: 'useEffect' },
  { id: 7, title: 'useEffect vs useLayoutEffect', section: 'useEffect' },
  { id: 8, title: 'Bẫy: effect chạy vô tận', section: 'useEffect' },
  { id: 9, title: 'useMemo — khi nào nên dùng', section: 'useMemo & useCallback' },
  { id: 10, title: 'useCallback — giữ stable reference', section: 'useMemo & useCallback' },
  { id: 11, title: 'Tại sao memo không luôn giúp ích', section: 'useMemo & useCallback' },
  { id: 12, title: 'useRef — trỏ đến DOM element', section: 'useRef & Custom' },
  { id: 13, title: 'useRef lưu giá trị giữa renders', section: 'useRef & Custom' },
  { id: 14, title: 'Custom hook — tách logic ra khỏi UI', section: 'useRef & Custom' },
  { id: 15, title: 'useContext — tránh prop drilling', section: 'useRef & Custom' },
]

const jsQuirksQuestions: Question[] = [
  { id: 1, title: '== vs === — khi nào khác nhau?', section: 'Coercion' },
  { id: 2, title: 'typeof null === "object" — tại sao?', section: 'Coercion' },
  { id: 3, title: 'NaN !== NaN — kiểm tra đúng cách', section: 'Coercion' },
  { id: 4, title: 'Hoisting — var vs let vs const', section: 'Scope & Hoisting' },
  { id: 5, title: 'Temporal Dead Zone (TDZ)', section: 'Scope & Hoisting' },
  { id: 6, title: 'this trong arrow function', section: 'Scope & Hoisting' },
  { id: 7, title: 'Closure — counter pattern', section: 'Scope & Hoisting' },
  { id: 8, title: 'Promise vs async/await', section: 'Async' },
  { id: 9, title: 'Event loop — call stack + task queue', section: 'Async' },
  { id: 10, title: 'Promise.all vs Promise.allSettled', section: 'Async' },
  { id: 11, title: 'setTimeout(fn, 0) — thứ tự thực thi', section: 'Async' },
]

const enIrregularQuestions: Question[] = [
  { id: 1, title: 'go / went / gone', section: 'Nhóm A→B→C' },
  { id: 2, title: 'take / took / taken', section: 'Nhóm A→B→C' },
  { id: 3, title: 'come / came / come', section: 'Nhóm A→B→A' },
  { id: 4, title: 'run / ran / run', section: 'Nhóm A→B→A' },
  { id: 5, title: 'cut / cut / cut', section: 'Nhóm A→A→A' },
  { id: 6, title: 'put / put / put', section: 'Nhóm A→A→A' },
  { id: 7, title: 'hit / hit / hit', section: 'Nhóm A→A→A' },
  { id: 8, title: 'see / saw / seen', section: 'Nhóm A→B→C' },
  { id: 9, title: 'break / broke / broken', section: 'Nhóm A→B→C' },
  { id: 10, title: 'know / knew / known', section: 'Nhóm A→B→C' },
  { id: 11, title: 'write / wrote / written', section: 'Nhóm A→B→C' },
  { id: 12, title: 'drive / drove / driven', section: 'Nhóm A→B→C' },
  { id: 13, title: 'begin / began / begun', section: 'Nhóm nguyên âm đổi' },
  { id: 14, title: 'sing / sang / sung', section: 'Nhóm nguyên âm đổi' },
  { id: 15, title: 'ring / rang / rung', section: 'Nhóm nguyên âm đổi' },
  { id: 16, title: 'swim / swam / swum', section: 'Nhóm nguyên âm đổi' },
  { id: 17, title: 'buy / bought / bought', section: 'Nhóm A→B→B' },
  { id: 18, title: 'bring / brought / brought', section: 'Nhóm A→B→B' },
  { id: 19, title: 'think / thought / thought', section: 'Nhóm A→B→B' },
  { id: 20, title: 'catch / caught / caught', section: 'Nhóm A→B→B' },
]

const animalJungleQuestions: Question[] = [
  { id: 1, title: 'Hổ Bengal — đặc điểm nhận dạng', section: 'Thú có vú' },
  { id: 2, title: 'Báo hoa mai vs báo đốm', section: 'Thú có vú' },
  { id: 3, title: 'Con lười — tại sao chuyển động chậm?', section: 'Thú có vú' },
  { id: 4, title: 'Gorilla — linh trưởng lớn nhất', section: 'Thú có vú' },
  { id: 5, title: 'Vẹt đuôi dài — loài nào biết nói nhất?', section: 'Chim' },
  { id: 6, title: 'Đại bàng — sải cánh rộng bao nhiêu?', section: 'Chim' },
  { id: 7, title: 'Toucan — chiếc mỏ khổng lồ có tác dụng gì?', section: 'Chim' },
  { id: 8, title: 'Rắn hổ mang chúa — nọc độc hoạt động thế nào', section: 'Bò sát' },
  { id: 9, title: 'Tắc kè — cơ chế đổi màu', section: 'Bò sát' },
  { id: 10, title: 'Cá sấu vs cá sấu mõm dài (gharial)', section: 'Bò sát' },
  { id: 11, title: 'Bướm Morpho — màu cánh từ đâu?', section: 'Côn trùng' },
  { id: 12, title: 'Kiến lá cutter — nông nghiệp trong tự nhiên', section: 'Côn trùng' },
]

const funTriviaQuestions: Question[] = [
  { id: 1, title: 'Hố đen — ánh sáng có thoát ra được không?', section: 'Vũ trụ' },
  { id: 2, title: 'Sao Neutron — mật độ vật chất so với thế nào?', section: 'Vũ trụ' },
  { id: 3, title: 'Ánh sáng từ Mặt Trời mất bao lâu đến Trái Đất?', section: 'Vũ trụ' },
  { id: 4, title: 'Ngân Hà có bao nhiêu ngôi sao?', section: 'Vũ trụ' },
  { id: 5, title: 'Tim đập bao nhiêu lần mỗi ngày?', section: 'Cơ thể người' },
  { id: 6, title: 'Não người nặng bao nhiêu?', section: 'Cơ thể người' },
  { id: 7, title: 'Xương nào nhỏ nhất trong cơ thể?', section: 'Cơ thể người' },
  { id: 8, title: 'Tế bào hồng cầu sống bao lâu?', section: 'Cơ thể người' },
  { id: 9, title: 'Nước chiếm bao nhiêu % trọng lượng cơ thể?', section: 'Cơ thể người' },
  { id: 10, title: 'Móng tay mọc nhanh hơn móng chân không?', section: 'Cơ thể người' },
  { id: 11, title: 'Cá có thể chết đuối không?', section: 'Sự thật thú vị' },
  { id: 12, title: 'Voi là động vật duy nhất không thể nhảy?', section: 'Sự thật thú vị' },
]

const cssModernQuestions: Question[] = [
  { id: 1, title: 'Grid — fr unit là gì?', section: 'Grid' },
  { id: 2, title: 'Grid — auto-fill vs auto-fit', section: 'Grid' },
  { id: 3, title: 'Grid — subgrid', section: 'Grid' },
  { id: 4, title: 'Flexbox — align-items vs align-content', section: 'Flexbox' },
  { id: 5, title: 'Flexbox — flex-grow, flex-shrink, flex-basis', section: 'Flexbox' },
  { id: 6, title: 'Container queries — @container', section: 'Responsive' },
  { id: 7, title: ':has() pseudo-class', section: 'Selectors' },
  { id: 8, title: ':is() và :where() — khác gì nhau?', section: 'Selectors' },
  { id: 9, title: 'color-mix() — pha màu trong CSS', section: 'Colors' },
  { id: 10, title: 'oklch() — không gian màu hiện đại', section: 'Colors' },
  { id: 11, title: 'CSS Cascade Layers — @layer', section: 'Architecture' },
  { id: 12, title: 'CSS Custom Properties — scope và inheritance', section: 'Architecture' },
  { id: 13, title: 'clamp() — fluid typography', section: 'Architecture' },
  { id: 14, title: 'logical properties — margin-inline', section: 'Architecture' },
]

export const QUIZ_SETS: QuizSet[] = [
  {
    id: 'ts-basics',
    category: 'code',
    title: 'TypeScript căn bản',
    desc: 'Type, interface, generic, narrowing — những thứ bạn dùng mỗi ngày.',
    icon: 'TS',
    iconMono: true,
    tint: '#dcd5ff',
    inkOfTint: '#3142a8',
    level: 'easy',
    questions: [],
    minutes: 15,
    progress: 0.62,
    section: 'đang học',
  },
  {
    id: 'react-hooks',
    category: 'code',
    title: 'React Hooks sâu',
    desc: 'useEffect, useMemo, useCallback và những bẫy quen thuộc.',
    icon: '⚛',
    tint: '#cfeeff',
    inkOfTint: '#0a6e90',
    level: 'mid',
    questions: reactHooksQuestions,
    minutes: 22,
    progress: 0.18,
    section: 'đang học',
  },
  {
    id: 'js-quirks',
    category: 'code',
    title: 'JavaScript kỳ quặc',
    desc: 'this, hoisting, closure, == vs === — những đoạn code khiến bạn bối rối.',
    icon: 'JS',
    iconMono: true,
    tint: '#fff1c2',
    inkOfTint: '#7d5c00',
    level: 'easy',
    questions: jsQuirksQuestions,
    minutes: 18,
    progress: 1,
    section: 'đã hoàn thành',
  },
  {
    id: 'css-modern',
    category: 'code',
    title: 'CSS hiện đại',
    desc: 'Grid, Flexbox, container query, :has(), color-mix() và các selector mới.',
    icon: '{ }',
    iconMono: true,
    tint: '#ffd6e9',
    inkOfTint: '#9c2865',
    level: 'mid',
    questions: cssModernQuestions,
    minutes: 20,
    progress: 0,
    section: 'khám phá',
    isNew: true,
  },
  {
    id: 'en-irregular',
    category: 'english',
    title: 'Động từ bất quy tắc',
    desc: 'go-went-gone, take-took-taken… 100 động từ phổ biến nhất.',
    icon: '🔤',
    tint: '#cfeeff',
    inkOfTint: '#0a6e90',
    level: 'easy',
    questions: enIrregularQuestions,
    minutes: 12,
    progress: 0.45,
    section: 'đang học',
  },
  {
    id: 'animal-jungle',
    category: 'animal',
    title: 'Động vật rừng nhiệt đới',
    desc: 'Báo, vẹt, lười, rắn… nhận biết qua hình ảnh và đặc điểm.',
    icon: '🦜',
    tint: '#cdf0c1',
    inkOfTint: '#1d6b2a',
    level: 'easy',
    questions: animalJungleQuestions,
    minutes: 14,
    progress: 0.3,
    section: 'đang học',
  },
  {
    id: 'fun-trivia',
    category: 'fun',
    title: 'Trivia kỳ quặc',
    desc: 'Sự thật bất ngờ về vũ trụ, cơ thể người, lịch sử... bạn có tin không?',
    icon: '🤔',
    tint: '#fff1c2',
    inkOfTint: '#7d5c00',
    level: 'mid',
    questions: funTriviaQuestions,
    minutes: 12,
    progress: 0.08,
    section: 'đang học',
  },
]
